
package xin.gonefuture.java.api.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloJws", targetNamespace = "http://webService.api.java.gonefuture.xin/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloJws {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://webService.api.java.gonefuture.xin/", className = "xin.gonefuture.java.api.webservice.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://webService.api.java.gonefuture.xin/", className = "xin.gonefuture.java.api.webservice.SayHelloResponse")
    @Action(input = "http://webService.api.java.gonefuture.xin/HelloJws/sayHelloRequest", output = "http://webService.api.java.gonefuture.xin/HelloJws/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBornDesc", targetNamespace = "http://webService.api.java.gonefuture.xin/", className = "xin.gonefuture.java.api.webservice.GetBornDesc")
    @ResponseWrapper(localName = "getBornDescResponse", targetNamespace = "http://webService.api.java.gonefuture.xin/", className = "xin.gonefuture.java.api.webservice.GetBornDescResponse")
    @Action(input = "http://webService.api.java.gonefuture.xin/HelloJws/getBornDescRequest", output = "http://webService.api.java.gonefuture.xin/HelloJws/getBornDescResponse")
    public String getBornDesc(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
