
package top.gonefuture.java.api.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloJwsService", targetNamespace = "http://webService.api.java.gonefuture.top/", wsdlLocation = "http://localhost:8080/hellojws?wsdl")
public class HelloJwsService
    extends Service
{

    private final static URL HELLOJWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOJWSSERVICE_EXCEPTION;
    private final static QName HELLOJWSSERVICE_QNAME = new QName("http://webService.api.java.gonefuture.top/", "HelloJwsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/hellojws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOJWSSERVICE_WSDL_LOCATION = url;
        HELLOJWSSERVICE_EXCEPTION = e;
    }

    public HelloJwsService() {
        super(__getWsdlLocation(), HELLOJWSSERVICE_QNAME);
    }

    public HelloJwsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOJWSSERVICE_QNAME, features);
    }

    public HelloJwsService(URL wsdlLocation) {
        super(wsdlLocation, HELLOJWSSERVICE_QNAME);
    }

    public HelloJwsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOJWSSERVICE_QNAME, features);
    }

    public HelloJwsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloJwsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloJws
     */
    @WebEndpoint(name = "HelloJwsPort")
    public HelloJws getHelloJwsPort() {
        return super.getPort(new QName("http://webService.api.java.gonefuture.top/", "HelloJwsPort"), HelloJws.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloJws
     */
    @WebEndpoint(name = "HelloJwsPort")
    public HelloJws getHelloJwsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webService.api.java.gonefuture.top/", "HelloJwsPort"), HelloJws.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOJWSSERVICE_EXCEPTION!= null) {
            throw HELLOJWSSERVICE_EXCEPTION;
        }
        return HELLOJWSSERVICE_WSDL_LOCATION;
    }

}
